import { config } from '@n8n/node-cli/eslint';

export default [
	...config,
	{
		ignores: ['scripts/**'],
	},
	{
		rules: {
			// Package rules
			'n8n-nodes-base/community-package-json-name-still-default': 'off',

			// Credentials rules
			'n8n-nodes-base/cred-class-field-authenticate-type-assertion': 'error',
			'n8n-nodes-base/cred-class-field-display-name-missing-oauth2': 'error',
			'n8n-nodes-base/cred-class-field-display-name-miscased': 'error',
			'n8n-nodes-base/cred-class-field-documentation-url-missing': 'error',
			'n8n-nodes-base/cred-class-field-documentation-url-miscased': 'off',
			'n8n-nodes-base/cred-class-field-name-missing-oauth2': 'error',
			'n8n-nodes-base/cred-class-field-name-unsuffixed': 'error',
			'n8n-nodes-base/cred-class-field-name-uppercase-first-char': 'error',
			'n8n-nodes-base/cred-class-field-properties-assertion': 'error',
			'n8n-nodes-base/cred-class-field-type-options-password-missing': 'off', // Triggers false positives on node properties
			'n8n-nodes-base/cred-class-name-missing-oauth2-suffix': 'error',
			'n8n-nodes-base/cred-class-name-unsuffixed': 'error',
			'n8n-nodes-base/cred-filename-against-convention': 'error',

			// Nodes rules
			'n8n-nodes-base/node-class-description-credentials-name-unsuffixed': 'error',
			'n8n-nodes-base/node-class-description-display-name-unsuffixed-trigger-node': 'error',
			'n8n-nodes-base/node-class-description-empty-string': 'error',
			'n8n-nodes-base/node-class-description-icon-not-svg': 'error',
			'n8n-nodes-base/node-class-description-inputs-wrong-regular-node': 'off',
			'n8n-nodes-base/node-class-description-inputs-wrong-trigger-node': 'error',
			'n8n-nodes-base/node-class-description-missing-subtitle': 'error',
			'n8n-nodes-base/node-class-description-non-core-color-present': 'error',
			'n8n-nodes-base/node-class-description-name-miscased': 'error',
			'n8n-nodes-base/node-class-description-name-unsuffixed-trigger-node': 'error',
			'n8n-nodes-base/node-class-description-outputs-wrong': 'off',
			'n8n-nodes-base/node-dirname-against-convention': 'error',
			'n8n-nodes-base/node-execute-block-double-assertion-for-items': 'error',
			'n8n-nodes-base/node-execute-block-wrong-error-thrown': 'error',
			'n8n-nodes-base/node-filename-against-convention': 'error',
			'n8n-nodes-base/node-param-array-type-assertion': 'error',
			'n8n-nodes-base/node-param-color-type-unused': 'error',
			'n8n-nodes-base/node-param-default-missing': 'error',
			'n8n-nodes-base/node-param-default-wrong-for-boolean': 'error',
			'n8n-nodes-base/node-param-default-wrong-for-collection': 'error',
			'n8n-nodes-base/node-param-default-wrong-for-fixed-collection': 'error',
			'n8n-nodes-base/node-param-default-wrong-for-fixed-collection': 'error',
			'n8n-nodes-base/node-param-default-wrong-for-multi-options': 'error',
			'n8n-nodes-base/node-param-default-wrong-for-number': 'error',
			'n8n-nodes-base/node-param-default-wrong-for-simplify': 'error',
			'n8n-nodes-base/node-param-default-wrong-for-string': 'error',
			'n8n-nodes-base/node-param-description-boolean-without-whether': 'warn',
			'n8n-nodes-base/node-param-description-comma-separated-hyphen': 'warn',
			'n8n-nodes-base/node-param-description-empty-string': 'error',
			'n8n-nodes-base/node-param-description-excess-final-period': 'warn',
			'n8n-nodes-base/node-param-description-excess-inner-whitespace': 'warn',
			'n8n-nodes-base/node-param-description-identical-to-display-name': 'error',
			'n8n-nodes-base/node-param-description-line-break-html-tag': 'warn',
			'n8n-nodes-base/node-param-description-lowercase-first-char': 'warn',
			'n8n-nodes-base/node-param-description-miscased-id': 'warn',
			'n8n-nodes-base/node-param-description-miscased-json': 'warn',
			'n8n-nodes-base/node-param-description-miscased-url': 'error',
			'n8n-nodes-base/node-param-description-missing-final-period': 'warn',
			'n8n-nodes-base/node-param-description-missing-for-ignore-ssl-issues': 'error',
			'n8n-nodes-base/node-param-description-missing-for-return-all': 'error',
			'n8n-nodes-base/node-param-description-missing-for-simplify': 'error',
			'n8n-nodes-base/node-param-description-missing-from-dynamic-multi-options': 'warn',
			'n8n-nodes-base/node-param-description-missing-from-dynamic-options': 'warn',
			'n8n-nodes-base/node-param-description-missing-from-limit': 'error',
			'n8n-nodes-base/node-param-description-unencoded-angle-brackets': 'warn',
			'n8n-nodes-base/node-param-description-unneeded-backticks': 'error',
			'n8n-nodes-base/node-param-description-untrimmed': 'warn',
			'n8n-nodes-base/node-param-description-url-missing-protocol': 'error',
			'n8n-nodes-base/node-param-description-weak': 'error',
			'n8n-nodes-base/node-param-description-wrong-for-dynamic-multi-options': 'warn',
			'n8n-nodes-base/node-param-description-wrong-for-dynamic-options': 'warn',
			'n8n-nodes-base/node-param-description-wrong-for-ignore-ssl-issues': 'error',
			'n8n-nodes-base/node-param-description-wrong-for-limit': 'error',
			'n8n-nodes-base/node-param-description-wrong-for-return-all': 'error',
			'n8n-nodes-base/node-param-description-wrong-for-simplify': 'error',
			'n8n-nodes-base/node-param-description-wrong-for-upsert': 'error',
			'n8n-nodes-base/node-param-display-name-excess-inner-whitespace': 'error',
			'n8n-nodes-base/node-param-display-name-miscased-id': 'warn',
			'n8n-nodes-base/node-param-display-name-miscased': 'warn',
			'n8n-nodes-base/node-param-display-name-not-first-position': 'error',
			'n8n-nodes-base/node-param-display-name-untrimmed': 'error',
			'n8n-nodes-base/node-param-display-name-wrong-for-dynamic-multi-options': 'warn',
			'n8n-nodes-base/node-param-display-name-wrong-for-dynamic-options': 'warn',
			'n8n-nodes-base/node-param-display-name-wrong-for-simplify': 'error',
			'n8n-nodes-base/node-param-display-name-wrong-for-update-fields': 'error',
			'n8n-nodes-base/node-param-min-value-wrong-for-limit': 'error',
			'n8n-nodes-base/node-param-multi-options-type-unsorted-items': 'warn',
			'n8n-nodes-base/node-param-name-untrimmed': 'error',
			'n8n-nodes-base/node-param-operation-option-action-miscased': 'warn',
			'n8n-nodes-base/node-param-operation-option-action-wrong-for-get-many': 'error',
			'n8n-nodes-base/node-param-operation-option-description-wrong-for-get-many': 'error',
			'n8n-nodes-base/node-param-operation-option-without-action': 'warn',
			'n8n-nodes-base/node-param-operation-without-no-data-expression': 'error',
			'n8n-nodes-base/node-param-option-description-identical-to-name': 'error',
			'n8n-nodes-base/node-param-option-name-containing-star': 'error',
			'n8n-nodes-base/node-param-option-name-duplicate': 'warn',
			'n8n-nodes-base/node-param-option-name-wrong-for-get-many': 'error',
			'n8n-nodes-base/node-param-option-name-wrong-for-upsert': 'error',
			'n8n-nodes-base/node-param-option-value-duplicate': 'warn',
			'n8n-nodes-base/node-param-options-type-unsorted-items': 'warn',
			'n8n-nodes-base/node-param-placeholder-miscased-id': 'warn',
			'n8n-nodes-base/node-param-placeholder-missing-email': 'error',
			'n8n-nodes-base/node-param-required-false': 'error',
			'n8n-nodes-base/node-param-resource-with-plural-option': 'warn',
			'n8n-nodes-base/node-param-resource-without-no-data-expression': 'error',
			'n8n-nodes-base/node-param-type-options-missing-from-limit': 'error',
			'n8n-nodes-base/node-param-type-options-password-missing': 'off', // Triggers false positives on 'key' fields
			'n8n-nodes-base/node-param-collection-type-unsorted-items': 'warn',
			'n8n-nodes-base/node-param-fixed-collection-type-unsorted-items': 'warn',
		},
	},
];
